Vagrant.configure(2) do |config|

  # RHEL 6
  config.vm.define "rhsub-rhel6" do |rhel6|
    rhel6.vm.box = "samdoran/rhel6"
    rhel6.vm.hostname = "rhsub-rhel6"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "rhsub-rhel7"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # RHEL 7
  config.vm.define "rhel7" do |rhel7|
    rhel7.vm.box = "samdoran/rhel7"
    rhel7.vm.hostname = "rhsub-rhel7"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "rhsub-rhel7"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
  end

end
