Vagrant.configure(2) do |config|

  # RHEL 6
  config.vm.define "rhsm-rhel6" do |rhel6|
    rhel6.vm.box = "samdoran/rhel6"
    rhel6.vm.hostname = "rhsm-rhel6"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "rhsm-rhel6"
      vbox.cpus = 1
      vbox.memory = 1024
    end
  end

  # RHEL 7
  config.vm.define "rhsm-rhel7" do |rhel7|
    rhel7.vm.box = "samdoran/rhel7"
    rhel7.vm.hostname = "rhsm-rhel7"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "rhsm-rhel7"
      vbox.cpus = 1
      vbox.memory = 1024
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = 'vagrant.yml'
    ansible.extra_vars = 'vars/portal.yml'
    ansible.compatibility_mode = '2.0'
  end
end
